#!/usr/bin/env python3

# INTEL CONFIDENTIAL

# © 2024 Intel Corporation
#
# This software and the related documents are Intel copyrighted materials, and
# your use of them is governed by the express license under which they were
# provided to you ("License"). Unless the License provides otherwise, you may
# not use, modify, copy, publish, distribute, disclose or transmit this software
# or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or
# implied warranties, other than those that are expressly stated in the License.

"""
Simple IP-XACT to DML generator.

This script parses an IP-XACT component file (memoryMaps/registers) and
generates two basic DML output files: <device>.dml and <device>-registers.dml.

Usage: python3 ipxact_gen.py <ipxact-xml> -o <simics_device_path> -d <device_name>
"""
import enum
import sys
import os
import argparse
import xml.etree.ElementTree as ET

# Inline minimal Output class and access mapping copied from osalgen.py
import io
import textwrap


class Output:
    def __init__(self, no_comments=False):
        self._io = io.StringIO()
        self._wr = self._io.write
        self.indent = 0
        self.bol = True
        self.no_comments = no_comments

    def contents(self):
        return self._io.getvalue()

    def clear(self):
        """Clear the contents and reset indent"""
        self._io = io.StringIO()
        self._wr = self._io.write
        self.indent = 0
        self.bol = True

    def write(self, s, *, pre=0, post=0):
        self.indent += pre * 4
        if s == '\n':
            self._wr('\n')
            self.bol = True
        elif s:
            if self.bol:
                self._wr(' ' * self.indent)
            self._wr(s)
            self.bol = s.endswith('\n')
        self.indent += post * 4

    def comments(self, desc, wraptext=textwrap.wrap):
        if not self.no_comments:
            if isinstance(desc, list):
                width = 78 - self.indent
                for line in desc:
                    for comment in wraptext(line.strip(), width):
                        self.write('// %s\n' % comment)
            elif desc:
                self.write('// %s\n' % desc)

    def _header(self, dev_name):
        self.write('/* -*- coding: utf-8 -*-\n')
        self.write('  This Software is part of Intel Simics. The rights to copy, distribute,\n')
        self.write('  modify, or otherwise make use of this Software may be licensed only\n')
        self.write('  pursuant to the terms of an applicable Intel license agreement.\n')
        self.write('\n')
        self.write('  © 2025 Intel Corporation\n')
        self.write('*/\n')
        self.write('// WARNING: This file is automatically generated from IP-XACT for %s\n' % dev_name)
        self.write('\n')
        self.write('dml 1.4;\n')

    def register_header(self, dev_name):
        self._header(dev_name)
        self.write('import "dml-builtins.dml";\n')
        self.write('import "utility.dml";\n')
        self.write('\n')

    def device_header(self, dev_name):
        self._header(dev_name)
        self.write(f'device {dev_name.replace("-", "_")};\n')
        self.write(f'import "{dev_name}-registers.dml";\n')
        self.write('import "simics/devs/signal.dml";\n')
        self.write('\n')


class Device:
    def __init__(self, name):
        self.name = name
        self.banks = []
        self.ports = []

    def to_dml(self, out):
        """Generate DML for this device"""
        out.device_header(self.name)
        out.comments('USER-TODO: add configuration attributes here, if needed.\n')
        out.comments(f'Basic bank declaration is in {self.name}-registers.dml,')
        out.comments('here is the register implementation with side-effects.')
        for bank in self.banks:
            out.write(f"bank {bank.name} is {bank.name}_temp")
            out.write(' {\n', post=1)
            for reg in bank.registers:
                if reg.comments:
                    out.write('register %s {\n' % reg.name, post=1)
                    if 'write-only' in reg.access or 'write' in reg.access:
                        out.write('method write_register(uint64 val, uint64 enabled_bytes, void *aux) {\n', post=1)
                        out.comments('USER-TODO: implement write side-effects for register %s here.' % reg.name)
                        out.comments(f'Description: {reg.comments}')
                        out.comments('Call default write behavior first')
                        out.write(f'default(val, enabled_bytes, aux);\n')
                        out.comments('USER-TODO: Add your implementation here.')
                        out.write('}\n', pre=-1)
                        out.write('\n')
                    if 'read-only' in reg.access or 'read' in reg.access:
                        out.write('method read_register(uint64 enabled_bytes, void *aux) -> (uint64) {\n', post=1)
                        out.comments('USER-TODO: implement read side-effects for register %s here.' % reg.name)
                        out.comments(f'Description: {reg.comments}')
                        out.comments('USER-TODO: Add your implementation here.')
                        out.write('return this.val;\n')
                        out.write('}\n', pre=-1)
                    out.write('}\n', pre=-1)
            out.write('}\n', pre=-1)
        out.write('\n')

        out.comments('Here are the signal interface implementations.')
        out.comments('port is for input signals, and connect is for output signal')
        for port in self.ports:
            if port.direction == PortDirection.IN:
                out.write(f'port {port.name}')
                out.write(' {\n', post=1)
                out.write('implement signal {\n', post=1)
                out.write(f"// USER-TODO: implement {port.name} signal handling here.\n")
                out.write('method signal_raise() {\n')
                out.write('}\n')
                out.write('method signal_lower() {\n')
                out.write('}\n')
                out.write('}\n', pre=-1)
                out.write('}\n', pre=-1)
            elif port.direction == PortDirection.OUT:
                out.write(f'connect {port.name}')
                out.write(' {\n', post=1)
                out.write(f'interface signal;\n')
                out.write('method signal_raise() {\n', post=1)
                out.write('this.signal.signal_raise();\n')
                out.write('}\n', pre=-1)
                out.write('method signal_lower() {\n', post=1)
                out.write('this.signal.signal_lower();\n')
                out.write('}\n', pre=-1)
                out.write('}\n', pre=-1)
        out.write('\n')
        out.comments('USER-TODO: add other connect and port definitions here, if needed.\n')

        out.comments('USER-TODO: add event declarations here, if needed.')
        out.comments('Here is a simple_time_event example:')
        out.comments('event timeout is (simple_time_event, hard_reset) {')
        out.comments('    method event() {')
        out.comments('        timer_done();')
        out.comments('    }')
        out.comments('    method schedule_timer(uint32 count) {')
        out.comments('        remove();')
        out.comments('        /* Adding +1 because the interrupt is triggered')
        out.comments('        * when the counter underflows')
        out.comments('        */')
        out.comments('        local double time_left = ((count + 1) / cast(FREQ_HZ.val, double));')
        out.comments('        post(time_left);')
        out.comments('    }')
        out.comments('    method hard_reset() {')
        out.comments('        remove();')
        out.comments('    }\n')
        out.comments('Here is a simple_cycle_event example:')
        out.comments('event timeout is simple_cycle_event {')
        out.comments('    method schedule() {')
        out.comments('        if (obj) {')
        out.comments('            remove();')
        out.comments('            local uint32 timeout = regs.reg_timeout_rst.val;')
        out.comments('            log info, 4: "%s event in %d cycles", qname, timeout;')
        out.comments('            post(timeout);')
        out.comments('      }')
        out.comments('    }')
        out.comments('    method event() {')
        out.comments('        log info, 4: "%s event fires", qname;')
        out.comments('        interrupt_raise();')
        out.comments('    }')
        out.comments('}\n')

        out.comments('USER-TODO: add common methods here, if needed\n')
        out.comments("USER-TODO: Add init() and post_init() methods here, if needed.")
        out.comments("init() will be run to set the empty state of the model, before any")
        out.comments("configuration or checkpointed attributes are set.  post_init() is run after")
        out.comments("all configuration attributes have been set.  This happens both when the")
        out.comments("initial configuration is set and when the configuration is loaded from a")
        out.comments("checkpoint.")

class PortDirection(enum.Enum):
    IN = 'in'
    OUT = 'out'
    INOUT = 'inout'

class Port:
    def __init__(self, name):
        self.name = name
        self.direction = PortDirection.IN

class Bank:
    def __init__(self, name):
        self.name = name
        self.base_address = 0
        self.registers = []

    def to_dml(self, out):
        """Generate DML for this bank"""
        # bank declaration
        out.write('template %s_temp {\n' % self.name, post=1)

        for r in self.registers:
            r.to_dml(out)

        out.write('}\n', pre=-1)

class Register:
    def __init__(self, name, offset, size, access):
        self.name = name
        self.offset = offset
        self.size = size
        self.access = access
        self.init_val = 0
        self.comments = ''
        self.fields = []

    def to_dml(self, out):
        """Generate DML for this register"""
        # register: size is in bytes, @ offset in hex
        size_bytes = self.size // 8 if self.size >= 8 else 1

        # register declaration with size and offset
        out.write('register %s size %d @ 0x%x' % (self.name, size_bytes, self.offset))
        out.write(' {\n', post=1)

        # Add desc parameter if we have comments
        if self.comments:
            out.comments(self.comments)
        out.write('param init_val = 0x%x;\n' % self.init_val)

        if not self.fields:
            for acc in self.access:
                out.write(f'is {acc};\n')

        # fields
        for f in self.fields:
            f.to_dml(out)

        out.write('}\n', pre=-1)

class Field:
    def __init__(self, name, bit_offset, bit_width, access):
        self.name = name
        self.bit_offset = bit_offset
        self.bit_width = bit_width
        self.init_val = 0
        self.access = access
        self.comments = ''

    def to_dml(self, out):
        """Generate DML for this field"""
        msb = self.bit_offset + self.bit_width - 1
        lsb = self.bit_offset

        # field declaration with bit range
        out.write('field %s @ [%d:%d]' % (self.name, msb, lsb))
        out.write(' {\n', post=1)

        # Add desc parameter if we have comments
        if self.comments:
            out.comments(self.comments)
        out.write('param init_val = 0x%x;\n' % self.init_val)
        for acc in self.access:
            out.write(f'is {acc};\n')
        out.write('}\n', pre=-1)

# minimal access mapping inspired from osalgen._access_template_map
_access_template_map = {
    'RO': ('read_only', 'READ_ONLY'),
    'RW': ('read_write', 'READ_WRITE'),
    'WO': ('write_only', 'WRITE_ONLY'),
    'NA': ('reserved', 'RESERVED'),
}


def access_template_name(acc):
    # accept either full key or simple ipxact strings
    if not acc:
        return None
    a = str(acc).upper().replace('-', '_')
    # try direct map
    if a in _access_template_map:
        return _access_template_map[a][0]
    # fallback basic heuristics
    la = a.lower()
    if 'read-only' in la or la == 'read_only' or la == 'readonly' or la == 'ro':
        return 'read_only'
    if 'write-only' in la or la == 'write_only' or la == 'writeonly' or la == 'wo':
        return 'write_only'
    return 'read_write'


def detect_ipxact_namespace(root):
    """Detect IP-XACT namespace version from the root element."""
    # Check the root tag for namespace
    tag = root.tag
    if '{' in tag:
        ns_uri = tag.split('}')[0].strip('{')
        return ns_uri

    # Try to detect from xmlns attributes
    for attr, value in root.attrib.items():
        if 'XMLSchema/IPXACT' in value:
            return value

    # Default to 1685-2022
    return 'http://www.accellera.org/XMLSchema/IPXACT/1685-2022'


def parse_ipxact_registers(xmlfile, device_name=None):
    tree = ET.parse(xmlfile)
    root = tree.getroot()

    # Auto-detect namespace version
    ns_uri = detect_ipxact_namespace(root)
    ns = {'ipxact': ns_uri}

    # device name - use provided name or extract from XML
    if device_name:
        dev_name = device_name
    else:
        comp_name = root.find('ipxact:name', ns)
        dev_name = comp_name.text.replace('_', '-') if comp_name is not None else 'component'
    device = Device(dev_name)

    # each memoryMap becomes a Bank; collect registers from all addressBlocks
    for memmap in root.findall('.//ipxact:memoryMap', ns):
        map_name = memmap.find('ipxact:name', ns)
        bank = Bank(map_name.text if map_name is not None else 'memoryMap')
        base_addr = 0

        # iterate all addressBlock entries under this memoryMap
        for addrblock in memmap.findall('.//ipxact:addressBlock', ns):
            base = addrblock.find('ipxact:baseAddress', ns)
            baseaddr = int(base.text, 0) if base is not None else 0
            base_addr = min(base_addr, baseaddr)

            for reg in addrblock.findall('ipxact:register', ns):
                name = reg.find('ipxact:name', ns)
                desc = reg.find('ipxact:description', ns)
                offset = reg.find('ipxact:addressOffset', ns)
                size = reg.find('ipxact:size', ns)
                access = reg.find('ipxact:access', ns)
                reset = reg.find('ipxact:reset', ns)

                roff = int(offset.text, 0) if offset is not None else 0
                rsize = int(size.text, 0) if size is not None else 32
                racc = (access.text or 'read-write') if access is not None else 'read-write'
                reg_access = ipxact_access_to_template(racc) if racc is not None else []

                # Extract reset value for register
                reg_reset_val = 0
                if reset is not None:
                    reset_value = reset.find('ipxact:value', ns)
                    if reset_value is not None and reset_value.text:
                        reg_reset_val = int(reset_value.text, 0)

                reg_obj = Register(name.text if name is not None else 'REG',
                                   baseaddr + roff,
                                   rsize,
                                   reg_access)
                reg_obj.comments = (desc.text or '') if desc is not None else ''
                reg_obj.init_val = reg_reset_val

                # fields
                for f in reg.findall('ipxact:field', ns):
                    fn = f.find('ipxact:name', ns)
                    fd = f.find('ipxact:description', ns)
                    bo = f.find('ipxact:bitOffset', ns)
                    bw = f.find('ipxact:bitWidth', ns)
                    fac = f.find('ipxact:access', ns)
                    access = ipxact_access_to_template(fac.text) if fac is not None else reg_access

                    bit_offset = int(bo.text, 0) if bo is not None else 0
                    bit_width = int(bw.text, 0) if bw is not None else 1

                    fobj = Field(fn.text if fn is not None else 'fld',
                                 bit_offset,
                                 bit_width,
                                 access)
                    fobj.comments = (fd.text or '') if fd is not None else ''

                    # Extract field init_val from register reset value
                    # Create a mask for the field bits and extract them
                    field_mask = (1 << bit_width) - 1
                    fobj.init_val = (reg_reset_val >> bit_offset) & field_mask

                    reg_obj.fields.append(fobj)

                bank.registers.append(reg_obj)
        bank.base_address = base_addr

        device.banks.append(bank)

    # Parse ports section
    for port_elem in root.findall('.//ipxact:port', ns):
        port_name_elem = port_elem.find('ipxact:name', ns)
        if port_name_elem is None:
            continue

        port = Port(port_name_elem.text)

        # Check for wire element and direction
        wire_elem = port_elem.find('ipxact:wire', ns)
        if wire_elem is not None:
            direction_elem = wire_elem.find('ipxact:direction', ns)
            if direction_elem is not None:
                direction_text = direction_elem.text.lower()
                if direction_text == 'in':
                    port.direction = PortDirection.IN
                elif direction_text == 'out':
                    port.direction = PortDirection.OUT
                elif direction_text == 'inout':
                    port.direction = PortDirection.INOUT
        device.ports.append(port)

    return device


def ipxact_access_to_template(access_text):
    # basic mapping: ipxact uses strings like 'read-only', 'write-only', 'read-write'
    # Note: 1685-2014 uses underscores (read_only), 1685-2022 uses hyphens (read-only)
    at = access_text.lower().replace('_', '-')  # normalize to hyphen format
    if 'read-only' in at or at == 'read-only' or at == 'readonly':
        return ['read','read_only']
    if 'write-only' in at or at == 'write-only' or at == 'writeonly':
        return ['write', 'write_only']
    # default to read-write
    return ['read', 'write']


def gen_dml_from_regs(dev, output_path):
    """Generate DML from Device object or legacy format"""
    if isinstance(dev, Device):
        reg_f = os.path.join(output_path, f"{dev.name}-registers.dml")
        dev_f = os.path.join(output_path, f"{dev.name}.dml")
        out = Output()
        out.register_header(dev.name)
        for bank in dev.banks:
            bank.to_dml(out)
            with open(reg_f, 'w') as f:
                f.write(out.contents())
        out.clear()
        dev.to_dml(out)
        with open(dev_f, 'w') as f:
            f.write(out.contents())
        return


def gen_test_from_xml(device, output_path):
    """Generate test files from Device object"""
    if not isinstance(device, Device):
        return

    # Create test directory if it doesn't exist
    test_dir = os.path.join(output_path, 'test')
    if not os.path.exists(test_dir):
        os.makedirs(test_dir)

    device_name = device.name.replace('-', '_')

    # Find output ports (connects) for fake PIC instances
    output_ports = [port for port in device.ports if port.direction == PortDirection.OUT]

    # Generate {device_name}_common.py
    common_file = os.path.join(test_dir, f"{device_name}_common.py")
    with open(common_file, 'w') as f:
        f.write("# © 2025-2026 Intel Corporation\n")
        f.write("# DO NOT edit this file, because it is generated automatically\n\n")
        f.write("import simics\n")
        f.write("import stest\n")
        f.write("import pyobj\n\n")

        f.write("# Ignore 'spec-viol' or 'unimpl' logs, test modeled behavior firstly\n")
        f.write("stest.untrap_log('spec-viol')\n")
        f.write("stest.untrap_log('unimpl')\n\n")

        f.write("class FakePic(pyobj.ConfObject):\n")
        f.write("    \"\"\"Fake interrupt controller\"\"\"\n")
        f.write("    \n")
        f.write("    class raised(pyobj.SimpleAttribute(0, 'i')): pass\n")
        f.write("    \n")
        f.write("    class signal(pyobj.Interface):\n")
        f.write("        def signal_raise(self):\n")
        f.write("            \"\"\"Called when device raises interrupt\"\"\"\n")
        f.write("            # Access the pyobj class attribute using `.val` inside the pyobj class\n")
        f.write("            self._up.raised.val += 1\n")
        f.write("            \n")
        f.write("        def signal_lower(self):\n")
        f.write("            \"\"\"Called when device lowers interrupt\"\"\"\n")
        f.write("            # Access the pyobj class attribute using `.val` inside the pyobj class\n")
        f.write("            self._up.raised.val -= 1\n\n")

        f.write("def create_config():\n")
        f.write("    # Create device\n")
        f.write(f"    dev = simics.pre_conf_object('dev', '{device_name}')\n")
        f.write("    clk = simics.pre_conf_object('clk', 'clock')\n")
        f.write("    mem = simics.pre_conf_object('mem', 'memory-space')\n")
        f.write("    \n")
        f.write("    # 2. Configure attributes BEFORE SIM_add_configuration\n")
        f.write("    clk.freq_mhz = 100  # ⚠️ CRITICAL: Set BEFORE instantiation\n")
        f.write("    dev.queue = clk     # REQUIRED for time-dependent devices\n")
        f.write("    \n")
        f.write("    # 3. Configure memory mapping\n")
        f.write("    mem.map = []\n")
        f.write("    # Map bank to memory space [base_addr, bank_obj, func, offset, size]\n")

        # Add memory mapping for each bank
        if device.banks:
            for bank in device.banks:
                # Calculate bank size (approximate from registers)
                bank_size = 0x1000  # Default size
                if bank.registers:
                    max_offset = max(reg.offset + (reg.size // 8) for reg in bank.registers)
                    bank_size = max(0x1000, (max_offset + 0xFFF) & ~0xFFF)  # Round up to 4KB
                f.write(f"    mem.map += [[0x{bank.base_address:x}, dev.bank.{bank.name}, 0, 0, 0x{bank_size:x}]]\n")
        else:
            f.write("    # mem.map += [[0x1000, dev.bank.bank_name, 0, 0, 0x1000]]  # TODO: Add bank mapping\n")
        f.write("    \n")
        
        # Create fake PIC instances for each output port
        if output_ports:
            f.write("    # Create fake PICs for output ports\n")
            for port in output_ports:
                f.write(f"    fake_pic_{port.name} = simics.pre_conf_object('fake_pic_{port.name}', 'FakePic')\n")
            f.write("    \n")
            
            f.write("    # Connect device output ports to fake PICs\n")
            for port in output_ports:
                f.write(f"    dev.{port.name} = fake_pic_{port.name}  # DML: connect {port.name} {{ ... }}\n")
            f.write("    \n")
        
        # Build configuration list
        f.write("    # Instantiate\n")
        config_list = "dev, clk, mem"
        if output_ports:
            config_list += ", " + ", ".join([f"fake_pic_{port.name}" for port in output_ports])
        f.write(f"    simics.SIM_add_configuration([{config_list}], None)\n")
        f.write("    \n")
        
        # Build return tuple
        return_tuple = "simics.SIM_get_object(dev.name)"
        if output_ports:
            pic_objects = ", ".join([f"simics.SIM_get_object(fake_pic_{port.name}.name)" for port in output_ports])
            return_tuple = f"({return_tuple}, {pic_objects})"
        else:
            return_tuple = f"({return_tuple}, None)"
        f.write(f"    return {return_tuple}\n")
    
    # Find a read-write register for the test
    rw_register = None
    register_bank_name = None
    for bank in device.banks:
        for reg in bank.registers:
            # Check if register has both read and write access
            if 'read' in reg.access and 'write' in reg.access:
                rw_register = reg.name
                register_bank_name = bank.name
                break
        if rw_register:
            break

    # If no RW register found, use the first register available
    if not rw_register and device.banks and device.banks[0].registers:
        rw_register = device.banks[0].registers[0].name
        register_bank_name = device.banks[0].name

    # Generate s-{device_name}.py
    test_file = os.path.join(test_dir, f"s-{device_name}.py")
    with open(test_file, 'w') as f:
        f.write("# © 2025-2026 Intel Corporation\n")
        f.write("# DO NOT edit this file, because it is generated automatically\n")
        f.write(f"# This is a basic example to demonstrate how to use {device_name}_common module\n")
        f.write(f"# It's an example to show how to access {device_name} register in python test, too\n\n")
        f.write("import dev_util\n")
        f.write("import simics\n")
        f.write("import conf\n")
        f.write("# Import stest module if using stest.expect_equal(val, expected_val) etc.\n")
        f.write("import stest\n")
        f.write(f"import {device_name}_common\n\n")

        f.write(f"def test_{device_name}():\n")
        f.write("    # Create an instance of the device to test\n")
        f.write(f"    devs = {device_name}_common.create_config()\n")
        f.write(f"    dev = devs[0]\n")

        # Add interrupt handling if there are output ports
        if output_ports:
            f.write(f"    connected_dev = devs[1]\n")
            f.write("\n")
            f.write("    # Access the pyobj class object attribute directly outside the class\n")
            f.write("    signal_raised_cnt = connected_dev.raised\n")
            f.write("    stest.expect_equal(signal_raised_cnt, 0)\n")

        f.write("\n")

        if rw_register and register_bank_name:
            f.write(f"    regs = dev_util.bank_regs(dev.bank.{register_bank_name})\n\n")
            f.write(f"    # Write/read a register of {device_name}\n")
            f.write("    written_val = 0xdeadbeef\n")
            f.write(f"    regs.{rw_register}.write(written_val)\n")
            f.write("    # Run 100 cycles/steps\n")
            f.write("    simics.SIM_continue(100)\n")
            f.write(f"    read_val = regs.{rw_register}.read()\n")
            f.write("    print(f'written_val: {written_val}')\n")
            f.write("    print(f'read_val: {read_val}')\n")
            f.write("    print('Test complete successfully!')\n")
        else:
            f.write("    # TODO: Add register access tests here\n")
            f.write("    # No read-write register found in the device\n")
            f.write("    print('No read-write register available for testing')\n")

        f.write("\n\n")
        f.write("if __name__ == \"__main__\":\n")
        f.write(f"    test_{device_name}()\n")

def main():
    p = argparse.ArgumentParser(description='Generate DML from IP-XACT.')
    p.add_argument('xml', help='IP-XACT xml file')
    p.add_argument('-o', '--output', help='Output path for DML files')
    p.add_argument('-d', '--device', help='Device name (overrides name from XML)')
    args = p.parse_args()

    device = parse_ipxact_registers(args.xml, args.device)
    gen_dml_from_regs(device, args.output)
    gen_test_from_xml(device, args.output)
    print(f"Generated DML files {args.device}.dml and {args.device}-registers.dml in '{args.output}'")
    print(f"Generated test files in '{args.output}/test/'")


if __name__ == '__main__':
    main()
