
# -*- makefile -*-
# Do not edit this file.
# This file will be overwritten by the project setup script.

RAW_SIMICS_BASE=/nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0
RAW_SIMICS_MODEL_BUILDER=/nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0
RAW_EML_PACKAGE=
RAW_DODOC_PKG=/nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0
RAW_PYTHON_PKG=/nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0/scripts/../../simics-python-7.13.0/linux64/bin/../..

RAW_SIMICS_PACKAGE_LIST=/nfs/site/disks/ssm_yongzhuo_001/ai_agents/tests/adk-mcp-rag/g5m_openspec_osdml/wdt_dbg152/adk_openspec_project/simics-project/.package-list

INCLUDE_PATHS = /nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0/src/include
CXX_INCLUDE_PATHS = /nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0/linux64/api
DML_INCLUDE_PATHS = /nfs/pdx/home/yongzhuo/.simics-mcp-server/simics-install/simics-7.57.0/linux64/bin/dml/api
HOST_TYPE = linux64
